# Generated by Django 6.0.6 on 2026-06-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('type', models.CharField(choices=[('RENTAL', 'Rental'), ('CANCELLATION_FEE', 'Cancellation Fee'), ('OVERDUE_FEE', 'Overdue Fee')], max_length=20)),
                ('session_url', models.URLField(max_length=500)),
                ('session_id', models.CharField(max_length=255)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
