# Generated by Django 6.0.6 on 2026-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('brand', 'model', 'year', 'fuel_type'), name='unique_car'),
        ),
    ]
