name: CI

on:
  push:
  pull_request:
    branches: [ "main", "develop" ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install flake8
        run: pip install flake8 flake8-quotes

      - name: Run flake8
        run: flake8 .


  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create .env
        run: |
          cat > .env << EOF
          DJANGO_DEBUG=False
          DJANGO_ALLOWED_HOSTS=localhost

          DJANGO_SECRET_KEY=test-secret-key

          POSTGRES_DB=test_db
          POSTGRES_USER=test_user
          POSTGRES_PASSWORD=test_password
          POSTGRES_HOST=db
          POSTGRES_PORT=5432
          EOF

      - name: Build
        run: docker compose build

      - name: Start database
        run: docker compose up -d db

      - name: Run tests
        run: docker compose run --rm app python manage.py test